artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/kraj2003/Mushroom_Classification/main/mushrooms.zip
  local_data_file: E:\Projects\Mushroom _classification\artifacts\data_ingestion\mushrooms.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_file: artifacts/data_ingestion/mushrooms.csv
  status_file : artifacts/data_validation/status.txt