artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kraj2003/Mushroom_Classification/blob/main/mushrooms.zip
  local_data_file: E:\Projects\Mushroom _classification\artifacts\data_ingestion\mushrooms.zip
  unzip_dir: artifacts/data_ingestion