artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/kraj2003/Mushroom_Classification/main/mushrooms.zip
  local_data_file: E:\Projects\Mushroom _classification\artifacts\data_ingestion\mushrooms.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_file: artifacts/data_ingestion/mushrooms.csv
  status_file : artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/mushrooms.csv
  final_model: artifacts/final_model
  preprocessor: final_model/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_arr: artifacts/data_transformation/train.npy
  test_arr: artifacts/data_transformation/test.npy
  model_name: model.joblib

model_eval:
  root_dir: artifacts/model_eval
  test_arr: artifacts/data_transformation/test.npy
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_eval/metrics.json